/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as SigninRouteImport } from './routes/signin'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as AuthenticatedChatRouteImport } from './routes/_authenticated/chat'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedEmailGeneratorRouteImport } from './routes/_authenticated/email-generator'
import { Route as AuthenticatedMeetingSummarizerRouteImport } from './routes/_authenticated/meeting-summarizer'
import { Route as AuthenticatedResearchAssistantRouteImport } from './routes/_authenticated/research-assistant'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedTaskPlannerRouteImport } from './routes/_authenticated/task-planner'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const SigninRoute = SigninRouteImport.update({
  id: '/signin',
  path: '/signin',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedChatRoute = AuthenticatedChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedEmailGeneratorRoute =
  AuthenticatedEmailGeneratorRouteImport.update({
    id: '/email-generator',
    path: '/email-generator',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMeetingSummarizerRoute =
  AuthenticatedMeetingSummarizerRouteImport.update({
    id: '/meeting-summarizer',
    path: '/meeting-summarizer',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedResearchAssistantRoute =
  AuthenticatedResearchAssistantRouteImport.update({
    id: '/research-assistant',
    path: '/research-assistant',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTaskPlannerRoute =
  AuthenticatedTaskPlannerRouteImport.update({
    id: '/task-planner',
    path: '/task-planner',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/signin': typeof SigninRoute
  '/signup': typeof SignupRoute
  '/chat': typeof AuthenticatedChatRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/email-generator': typeof AuthenticatedEmailGeneratorRoute
  '/meeting-summarizer': typeof AuthenticatedMeetingSummarizerRoute
  '/research-assistant': typeof AuthenticatedResearchAssistantRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/task-planner': typeof AuthenticatedTaskPlannerRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/signin': typeof SigninRoute
  '/signup': typeof SignupRoute
  '/chat': typeof AuthenticatedChatRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/email-generator': typeof AuthenticatedEmailGeneratorRoute
  '/meeting-summarizer': typeof AuthenticatedMeetingSummarizerRoute
  '/research-assistant': typeof AuthenticatedResearchAssistantRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/task-planner': typeof AuthenticatedTaskPlannerRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/signin': typeof SigninRoute
  '/signup': typeof SignupRoute
  '/_authenticated/chat': typeof AuthenticatedChatRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/email-generator': typeof AuthenticatedEmailGeneratorRoute
  '/_authenticated/meeting-summarizer': typeof AuthenticatedMeetingSummarizerRoute
  '/_authenticated/research-assistant': typeof AuthenticatedResearchAssistantRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/task-planner': typeof AuthenticatedTaskPlannerRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/signin'
    | '/signup'
    | '/chat'
    | '/dashboard'
    | '/email-generator'
    | '/meeting-summarizer'
    | '/research-assistant'
    | '/settings'
    | '/task-planner'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/signin'
    | '/signup'
    | '/chat'
    | '/dashboard'
    | '/email-generator'
    | '/meeting-summarizer'
    | '/research-assistant'
    | '/settings'
    | '/task-planner'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/signin'
    | '/signup'
    | '/_authenticated/chat'
    | '/_authenticated/dashboard'
    | '/_authenticated/email-generator'
    | '/_authenticated/meeting-summarizer'
    | '/_authenticated/research-assistant'
    | '/_authenticated/settings'
    | '/_authenticated/task-planner'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  SigninRoute: typeof SigninRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signin': {
      id: '/signin'
      path: '/signin'
      fullPath: '/signin'
      preLoaderRoute: typeof SigninRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/chat': {
      id: '/_authenticated/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof AuthenticatedChatRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/email-generator': {
      id: '/_authenticated/email-generator'
      path: '/email-generator'
      fullPath: '/email-generator'
      preLoaderRoute: typeof AuthenticatedEmailGeneratorRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/meeting-summarizer': {
      id: '/_authenticated/meeting-summarizer'
      path: '/meeting-summarizer'
      fullPath: '/meeting-summarizer'
      preLoaderRoute: typeof AuthenticatedMeetingSummarizerRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/research-assistant': {
      id: '/_authenticated/research-assistant'
      path: '/research-assistant'
      fullPath: '/research-assistant'
      preLoaderRoute: typeof AuthenticatedResearchAssistantRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/task-planner': {
      id: '/_authenticated/task-planner'
      path: '/task-planner'
      fullPath: '/task-planner'
      preLoaderRoute: typeof AuthenticatedTaskPlannerRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedChatRoute: typeof AuthenticatedChatRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedEmailGeneratorRoute: typeof AuthenticatedEmailGeneratorRoute
  AuthenticatedMeetingSummarizerRoute: typeof AuthenticatedMeetingSummarizerRoute
  AuthenticatedResearchAssistantRoute: typeof AuthenticatedResearchAssistantRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedTaskPlannerRoute: typeof AuthenticatedTaskPlannerRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedChatRoute: AuthenticatedChatRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedEmailGeneratorRoute: AuthenticatedEmailGeneratorRoute,
  AuthenticatedMeetingSummarizerRoute: AuthenticatedMeetingSummarizerRoute,
  AuthenticatedResearchAssistantRoute: AuthenticatedResearchAssistantRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedTaskPlannerRoute: AuthenticatedTaskPlannerRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  SigninRoute: SigninRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
